#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : readme_renderer
Version  : 24.0
Release  : 1
URL      : https://files.pythonhosted.org/packages/44/de/a567140b13a0fc8d3b04d85a510b5a7d9869b44b2939fa8ac07c5e421485/readme_renderer-24.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/44/de/a567140b13a0fc8d3b04d85a510b5a7d9869b44b2939fa8ac07c5e421485/readme_renderer-24.0.tar.gz
Summary  : readme_renderer is a library for rendering "readme" descriptions for Warehouse
Group    : Development/Tools
License  : Apache-2.0
Requires: readme_renderer-license = %{version}-%{release}
Requires: readme_renderer-python = %{version}-%{release}
Requires: readme_renderer-python3 = %{version}-%{release}
Requires: Pygments
Requires: bleach
Requires: docutils
Requires: six
BuildRequires : Pygments
BuildRequires : bleach
BuildRequires : buildreq-distutils3
BuildRequires : docutils
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : six
BuildRequires : tox
BuildRequires : virtualenv

%description
Readme Renderer
===============

Readme Renderer is a library that will safely render arbitrary
``README`` files into HTML. It is designed to be used in Warehouse_ to
render the ``long_description`` for packages. It can handle Markdown,
reStructuredText (``.rst``), and plain text.

.. _Warehouse: https://github.com/pypa/warehouse


Check Description Locally
-------------------------

To locally check whether your long descriptions will render on PyPI, first
build your distributions, and then use the |twine check|_ command.


Code of Conduct
---------------

Everyone interacting in the readme_renderer project's codebases, issue trackers,
chat rooms, and mailing lists is expected to follow the `PyPA Code of Conduct`_.


.. |twine check| replace:: ``twine check``
.. _twine check: https://packaging.python.org/guides/making-a-pypi-friendly-readme#validating-restructuredtext-markup
.. _PyPA Code of Conduct: https://www.pypa.io/en/latest/code-of-conduct/

%package license
Summary: license components for the readme_renderer package.
Group: Default

%description license
license components for the readme_renderer package.


%package python
Summary: python components for the readme_renderer package.
Group: Default
Requires: readme_renderer-python3 = %{version}-%{release}

%description python
python components for the readme_renderer package.


%package python3
Summary: python3 components for the readme_renderer package.
Group: Default
Requires: python3-core
Provides: pypi(readme_renderer)
Requires: pypi(Pygments)
Requires: pypi(cmarkgfm)
Requires: pypi(six)
Requires: pypi(docutils)
Requires: pypi(bleach)

%description python3
python3 components for the readme_renderer package.


%prep
%setup -q -n readme_renderer-24.0
cd %{_builddir}/readme_renderer-24.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1583296752
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/readme_renderer
cp %{_builddir}/readme_renderer-24.0/LICENSE %{buildroot}/usr/share/package-licenses/readme_renderer/43a3a49bd7af636c923a5ae475395b8e29320529
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/readme_renderer/43a3a49bd7af636c923a5ae475395b8e29320529

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
